/**********************************
 * Autogenerated -- do not modify *
 **********************************/

#ifndef UA_NODEIDS_EXAMPLE_NS_H_
#define UA_NODEIDS_EXAMPLE_NS_H_

/**
 * Namespace Zero NodeIds
 * ----------------------
 * Numeric identifiers of standard-defined nodes in namespace zero. The
 * following definitions are autogenerated from a CSV file */

#define UA_EXAMPLE_NSID_TESTTYPE 1001 /* ObjectType */
#define UA_EXAMPLE_NSID_TESTINSTANCE 5001 /* Object */
#define UA_EXAMPLE_NSID_TESTFOLDER 5002 /* Object */
#define UA_EXAMPLE_NSID_TESTTYPE_VAR1 6001 /* Variable */
#define UA_EXAMPLE_NSID_TESTINSTANCE_VAR1 6002 /* Variable */
#endif /* UA_NODEIDS_EXAMPLE_NS_H_ */ 
