/**********************************
 * Autogenerated -- do not modify *
 **********************************/

#ifndef UA_NODEIDS_TESTNODESET_H_
#define UA_NODEIDS_TESTNODESET_H_

/**
 * Namespace Zero NodeIds
 * ----------------------
 * Numeric identifiers of standard-defined nodes in namespace zero. The
 * following definitions are autogenerated from a CSV file */

#define UA_TESTNODESETID_STRUCTS 5001 /* Object */
#define UA_TESTNODESETID_POINT_ENCODING_DEFAULTBINARY 5002 /* Object */
#define UA_TESTNODESETID_NESTEDPOINT_ENCODING_DEFAULTBINARY 5003 /* Object */
#define UA_TESTNODESETID_POINTWITHARRAY_ENCODING_DEFAULTBINARY 5004 /* Object */
#define UA_TESTNODESETID_BASEDATATYPES 5100 /* Object */
#define UA_TESTNODESETID_BASEDATATYPES_DOUBLE 5101 /* Variable */
#define UA_TESTNODESETID_BASEDATATYPES_UINT32 5102 /* Variable */
#define UA_TESTNODESETID_POINT 10001 /* DataType */
#define UA_TESTNODESETID_STRUCTS_POINTA 10002 /* Variable */
#define UA_TESTNODESETID_STRUCTS_POINTC_ARRAY 10004 /* Variable */
#define UA_TESTNODESETID_STRUCTS_POINTB 10005 /* Variable */
#define UA_TESTNODESETID_STRUCTS_INPUTARGUMENTS 11493 /* Variable */
#define UA_TESTNODESETID_STRUCTS_STATICNODEIDTYPES 15962 /* Variable */
#define UA_TESTNODESETID_STRUCTS_STATICNODEIDTYPES 15963 /* Variable */
#define UA_TESTNODESETID_BASEDATATYPES_STRING1_SCALAR 16001 /* Variable */
#define UA_TESTNODESETID_BASEDATATYPES_BYTESTRING_SCALAR 16002 /* Variable */
#define UA_TESTNODESETID_POINTWITHARRAY 3003 /* DataType */
#define UA_TESTNODESETID_NESTEDPOINT 10008 /* DataType */
#define UA_TESTNODESETID_POINTWITHPOINTARRAY 3004 /* DataType */
#endif /* UA_NODEIDS_TESTNODESET_H_ */ 
