/**********************************
 * Autogenerated -- do not modify *
 **********************************/

#include "types_powerlink_generated.h"

/* ErrorRegisterBits */
static UA_DataTypeMember ErrorRegisterBits_members[2] = {
{
    UA_TYPENAME("Value") /* .memberName */
    &UA_TYPES[UA_TYPES_BYTESTRING], /* .memberType */
    0, /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("ValidBits") /* .memberName */
    &UA_TYPES[UA_TYPES_BYTESTRING], /* .memberType */
    offsetof(UA_ErrorRegisterBits, validBits) - offsetof(UA_ErrorRegisterBits, value) - sizeof(UA_ByteString), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},};

/* PowerlinkAttribute */
static UA_DataTypeMember PowerlinkAttribute_members[2] = {
{
    UA_TYPENAME("Value") /* .memberName */
    &UA_TYPES[UA_TYPES_BYTESTRING], /* .memberType */
    0, /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("ValidBits") /* .memberName */
    &UA_TYPES[UA_TYPES_BYTESTRING], /* .memberType */
    offsetof(UA_PowerlinkAttribute, validBits) - offsetof(UA_PowerlinkAttribute, value) - sizeof(UA_ByteString), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},};

/* PowerlinkErrorEntryDataType */
static UA_DataTypeMember PowerlinkErrorEntryDataType_members[4] = {
{
    UA_TYPENAME("EntryType") /* .memberName */
    &UA_TYPES[UA_TYPES_UINT16], /* .memberType */
    0, /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("ErrorCode") /* .memberName */
    &UA_TYPES[UA_TYPES_UINT16], /* .memberType */
    offsetof(UA_PowerlinkErrorEntryDataType, errorCode) - offsetof(UA_PowerlinkErrorEntryDataType, entryType) - sizeof(UA_UInt16), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("TimeStamp") /* .memberName */
    &UA_TYPES[UA_TYPES_UINT64], /* .memberType */
    offsetof(UA_PowerlinkErrorEntryDataType, timeStamp) - offsetof(UA_PowerlinkErrorEntryDataType, errorCode) - sizeof(UA_UInt16), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("AdditionalInformation") /* .memberName */
    &UA_TYPES[UA_TYPES_UINT64], /* .memberType */
    offsetof(UA_PowerlinkErrorEntryDataType, additionalInformation) - offsetof(UA_PowerlinkErrorEntryDataType, timeStamp) - sizeof(UA_UInt64), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},};

/* PowerlinkIpAddressDataType */
static UA_DataTypeMember PowerlinkIpAddressDataType_members[4] = {
{
    UA_TYPENAME("B1") /* .memberName */
    &UA_TYPES[UA_TYPES_BYTE], /* .memberType */
    0, /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("B2") /* .memberName */
    &UA_TYPES[UA_TYPES_BYTE], /* .memberType */
    offsetof(UA_PowerlinkIpAddressDataType, b2) - offsetof(UA_PowerlinkIpAddressDataType, b1) - sizeof(UA_Byte), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("B3") /* .memberName */
    &UA_TYPES[UA_TYPES_BYTE], /* .memberType */
    offsetof(UA_PowerlinkIpAddressDataType, b3) - offsetof(UA_PowerlinkIpAddressDataType, b2) - sizeof(UA_Byte), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("B4") /* .memberName */
    &UA_TYPES[UA_TYPES_BYTE], /* .memberType */
    offsetof(UA_PowerlinkIpAddressDataType, b4) - offsetof(UA_PowerlinkIpAddressDataType, b3) - sizeof(UA_Byte), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},};

/* PowerlinkPDOMappingEntryDataType */
static UA_DataTypeMember PowerlinkPDOMappingEntryDataType_members[5] = {
{
    UA_TYPENAME("Length") /* .memberName */
    &UA_TYPES[UA_TYPES_UINT16], /* .memberType */
    0, /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("Offset") /* .memberName */
    &UA_TYPES[UA_TYPES_UINT16], /* .memberType */
    offsetof(UA_PowerlinkPDOMappingEntryDataType, offset) - offsetof(UA_PowerlinkPDOMappingEntryDataType, length) - sizeof(UA_UInt16), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("Reserved") /* .memberName */
    &UA_TYPES[UA_TYPES_BYTE], /* .memberType */
    offsetof(UA_PowerlinkPDOMappingEntryDataType, reserved) - offsetof(UA_PowerlinkPDOMappingEntryDataType, offset) - sizeof(UA_UInt16), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("SubIndex") /* .memberName */
    &UA_TYPES[UA_TYPES_BYTE], /* .memberType */
    offsetof(UA_PowerlinkPDOMappingEntryDataType, subIndex) - offsetof(UA_PowerlinkPDOMappingEntryDataType, reserved) - sizeof(UA_Byte), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("Index") /* .memberName */
    &UA_TYPES[UA_TYPES_UINT16], /* .memberType */
    offsetof(UA_PowerlinkPDOMappingEntryDataType, index) - offsetof(UA_PowerlinkPDOMappingEntryDataType, subIndex) - sizeof(UA_Byte), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},};

/* PowerlinkNMTResetCmdEnumeration */
#define PowerlinkNMTResetCmdEnumeration_members NULL

/* PowerlinkNMTStateEnumeration */
#define PowerlinkNMTStateEnumeration_members NULL
const UA_DataType UA_TYPES_POWERLINK[UA_TYPES_POWERLINK_COUNT] = {
/* ErrorRegisterBits */
{
    UA_TYPENAME("ErrorRegisterBits") /* .typeName */
    {3, UA_NODEIDTYPE_NUMERIC, {26LU}}, /* .typeId */
    {3, UA_NODEIDTYPE_NUMERIC, {36LU}}, /* .binaryEncodingId */
    sizeof(UA_ErrorRegisterBits), /* .memSize */
    UA_DATATYPEKIND_STRUCTURE, /* .typeKind */
    false, /* .pointerFree */
    false, /* .overlayable */
    2, /* .membersSize */
    ErrorRegisterBits_members  /* .members */
},
/* PowerlinkAttribute */
{
    UA_TYPENAME("PowerlinkAttribute") /* .typeName */
    {3, UA_NODEIDTYPE_NUMERIC, {25LU}}, /* .typeId */
    {3, UA_NODEIDTYPE_NUMERIC, {33LU}}, /* .binaryEncodingId */
    sizeof(UA_PowerlinkAttribute), /* .memSize */
    UA_DATATYPEKIND_STRUCTURE, /* .typeKind */
    false, /* .pointerFree */
    false, /* .overlayable */
    2, /* .membersSize */
    PowerlinkAttribute_members  /* .members */
},
/* PowerlinkErrorEntryDataType */
{
    UA_TYPENAME("PowerlinkErrorEntryDataType") /* .typeName */
    {3, UA_NODEIDTYPE_NUMERIC, {27LU}}, /* .typeId */
    {3, UA_NODEIDTYPE_NUMERIC, {53LU}}, /* .binaryEncodingId */
    sizeof(UA_PowerlinkErrorEntryDataType), /* .memSize */
    UA_DATATYPEKIND_STRUCTURE, /* .typeKind */
    true, /* .pointerFree */
    false, /* .overlayable */
    4, /* .membersSize */
    PowerlinkErrorEntryDataType_members  /* .members */
},
/* PowerlinkIpAddressDataType */
{
    UA_TYPENAME("PowerlinkIpAddressDataType") /* .typeName */
    {3, UA_NODEIDTYPE_NUMERIC, {29LU}}, /* .typeId */
    {3, UA_NODEIDTYPE_NUMERIC, {32LU}}, /* .binaryEncodingId */
    sizeof(UA_PowerlinkIpAddressDataType), /* .memSize */
    UA_DATATYPEKIND_STRUCTURE, /* .typeKind */
    true, /* .pointerFree */
    false, /* .overlayable */
    4, /* .membersSize */
    PowerlinkIpAddressDataType_members  /* .members */
},
/* PowerlinkPDOMappingEntryDataType */
{
    UA_TYPENAME("PowerlinkPDOMappingEntryDataType") /* .typeName */
    {3, UA_NODEIDTYPE_NUMERIC, {30LU}}, /* .typeId */
    {3, UA_NODEIDTYPE_NUMERIC, {40LU}}, /* .binaryEncodingId */
    sizeof(UA_PowerlinkPDOMappingEntryDataType), /* .memSize */
    UA_DATATYPEKIND_STRUCTURE, /* .typeKind */
    true, /* .pointerFree */
    false, /* .overlayable */
    5, /* .membersSize */
    PowerlinkPDOMappingEntryDataType_members  /* .members */
},
/* PowerlinkNMTResetCmdEnumeration */
{
    UA_TYPENAME("PowerlinkNMTResetCmdEnumeration") /* .typeName */
    {3, UA_NODEIDTYPE_NUMERIC, {28LU}}, /* .typeId */
    {3, UA_NODEIDTYPE_NUMERIC, {0}}, /* .binaryEncodingId */
    sizeof(UA_PowerlinkNMTResetCmdEnumeration), /* .memSize */
    UA_DATATYPEKIND_ENUM, /* .typeKind */
    true, /* .pointerFree */
    UA_BINARY_OVERLAYABLE_INTEGER, /* .overlayable */
    0, /* .membersSize */
    PowerlinkNMTResetCmdEnumeration_members  /* .members */
},
/* PowerlinkNMTStateEnumeration */
{
    UA_TYPENAME("PowerlinkNMTStateEnumeration") /* .typeName */
    {3, UA_NODEIDTYPE_NUMERIC, {24LU}}, /* .typeId */
    {3, UA_NODEIDTYPE_NUMERIC, {0}}, /* .binaryEncodingId */
    sizeof(UA_PowerlinkNMTStateEnumeration), /* .memSize */
    UA_DATATYPEKIND_ENUM, /* .typeKind */
    true, /* .pointerFree */
    UA_BINARY_OVERLAYABLE_INTEGER, /* .overlayable */
    0, /* .membersSize */
    PowerlinkNMTStateEnumeration_members  /* .members */
},
};

