/**********************************
 * Autogenerated -- do not modify *
 **********************************/

#include "types_testnodeset_generated.h"

/* Point */
static UA_DataTypeMember Point_members[2] = {
{
    UA_TYPENAME("X") /* .memberName */
    &UA_TYPES[UA_TYPES_DOUBLE], /* .memberType */
    0, /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("Y") /* .memberName */
    &UA_TYPES[UA_TYPES_DOUBLE], /* .memberType */
    offsetof(UA_Point, y) - offsetof(UA_Point, x) - sizeof(UA_Double), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},};

/* NestedPoint */
static UA_DataTypeMember NestedPoint_members[3] = {
{
    UA_TYPENAME("X") /* .memberName */
    &UA_TYPES[UA_TYPES_DOUBLE], /* .memberType */
    0, /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("Y") /* .memberName */
    &UA_TYPES[UA_TYPES_DOUBLE], /* .memberType */
    offsetof(UA_NestedPoint, y) - offsetof(UA_NestedPoint, x) - sizeof(UA_Double), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("Point1") /* .memberName */
    &UA_TYPES_TESTNODESET[UA_TYPES_TESTNODESET_POINT], /* .memberType */
    offsetof(UA_NestedPoint, point1) - offsetof(UA_NestedPoint, y) - sizeof(UA_Double), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},};

/* PointWithArray */
static UA_DataTypeMember PointWithArray_members[4] = {
{
    UA_TYPENAME("X") /* .memberName */
    &UA_TYPES[UA_TYPES_DOUBLE], /* .memberType */
    0, /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("Y") /* .memberName */
    &UA_TYPES[UA_TYPES_DOUBLE], /* .memberType */
    offsetof(UA_PointWithArray, y) - offsetof(UA_PointWithArray, x) - sizeof(UA_Double), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("Z") /* .memberName */
    &UA_TYPES[UA_TYPES_DOUBLE], /* .memberType */
    offsetof(UA_PointWithArray, z) - offsetof(UA_PointWithArray, y) - sizeof(UA_Double), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("Array1") /* .memberName */
    &UA_TYPES[UA_TYPES_DOUBLE], /* .memberType */
    offsetof(UA_PointWithArray, array1Size) - offsetof(UA_PointWithArray, z) - sizeof(UA_Double), /* .padding */
    true, /* .isArray */
    false  /* .isOptional */
},};

/* PointWithPointArray */
static UA_DataTypeMember PointWithPointArray_members[4] = {
{
    UA_TYPENAME("X") /* .memberName */
    &UA_TYPES[UA_TYPES_DOUBLE], /* .memberType */
    0, /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("Y") /* .memberName */
    &UA_TYPES[UA_TYPES_DOUBLE], /* .memberType */
    offsetof(UA_PointWithPointArray, y) - offsetof(UA_PointWithPointArray, x) - sizeof(UA_Double), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("Z") /* .memberName */
    &UA_TYPES[UA_TYPES_DOUBLE], /* .memberType */
    offsetof(UA_PointWithPointArray, z) - offsetof(UA_PointWithPointArray, y) - sizeof(UA_Double), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("Array1") /* .memberName */
    &UA_TYPES_TESTNODESET[UA_TYPES_TESTNODESET_POINT], /* .memberType */
    offsetof(UA_PointWithPointArray, array1Size) - offsetof(UA_PointWithPointArray, z) - sizeof(UA_Double), /* .padding */
    true, /* .isArray */
    false  /* .isOptional */
},};
const UA_DataType UA_TYPES_TESTNODESET[UA_TYPES_TESTNODESET_COUNT] = {
/* Point */
{
    UA_TYPENAME("Point") /* .typeName */
    {2, UA_NODEIDTYPE_NUMERIC, {10001LU}}, /* .typeId */
    {2, UA_NODEIDTYPE_NUMERIC, {5002LU}}, /* .binaryEncodingId */
    sizeof(UA_Point), /* .memSize */
    UA_DATATYPEKIND_STRUCTURE, /* .typeKind */
    true, /* .pointerFree */
    false, /* .overlayable */
    2, /* .membersSize */
    Point_members  /* .members */
},
/* NestedPoint */
{
    UA_TYPENAME("NestedPoint") /* .typeName */
    {2, UA_NODEIDTYPE_NUMERIC, {10008LU}}, /* .typeId */
    {2, UA_NODEIDTYPE_NUMERIC, {5003LU}}, /* .binaryEncodingId */
    sizeof(UA_NestedPoint), /* .memSize */
    UA_DATATYPEKIND_STRUCTURE, /* .typeKind */
    true, /* .pointerFree */
    false, /* .overlayable */
    3, /* .membersSize */
    NestedPoint_members  /* .members */
},
/* PointWithArray */
{
    UA_TYPENAME("PointWithArray") /* .typeName */
    {2, UA_NODEIDTYPE_NUMERIC, {3003LU}}, /* .typeId */
    {2, UA_NODEIDTYPE_NUMERIC, {5004LU}}, /* .binaryEncodingId */
    sizeof(UA_PointWithArray), /* .memSize */
    UA_DATATYPEKIND_STRUCTURE, /* .typeKind */
    false, /* .pointerFree */
    false, /* .overlayable */
    4, /* .membersSize */
    PointWithArray_members  /* .members */
},
/* PointWithPointArray */
{
    UA_TYPENAME("PointWithPointArray") /* .typeName */
    {2, UA_NODEIDTYPE_NUMERIC, {3004LU}}, /* .typeId */
    {2, UA_NODEIDTYPE_NUMERIC, {0}}, /* .binaryEncodingId */
    sizeof(UA_PointWithPointArray), /* .memSize */
    UA_DATATYPEKIND_STRUCTURE, /* .typeKind */
    false, /* .pointerFree */
    false, /* .overlayable */
    4, /* .membersSize */
    PointWithPointArray_members  /* .members */
},
};

